__author__ = "Erich Nguyen, Johan Joseph, and Hrishikesh Kondiboyina"
__discord__ = ["GoogleGenius#3876", "johann#2022", "hrish#7294"]
__copyright__ = "Copyright 2022-Present Scripty Development"
__credits__ = []
__license__ = "Apache License Version 2.0"
__version__ = "1.0.0a5"
__maintainer__ = "Erich Nguyen"
__email__ = "nverich07@gmail.com"
__status__ = "Development"
